import { describe, expect, it } from "vitest";
import { CommandService } from "../domain/commands";
import { createInitialState } from "../state/reducer";
import { createStore } from "../state/store";

function harness(now = 1_000) { const store = createStore(createInitialState()); let id = 0; return { store, service: new CommandService(store, { now: () => now, id: () => `id-${++id}` }) }; }

describe("deal command safety", () => {
  it("inspects without changing state", () => { const { store, service } = harness(); const before = store.getState(); expect(service.inspectExchange().ok).toBe(true); expect(store.getState()).toBe(before); });
  it("searches, compares, and visibly recommends MetroPulse", () => { const { store, service } = harness(); expect(service.searchDataOffers({ query: "Sydney foot traffic", maxCredits: 40 }).ok).toBe(true); expect(service.compareDataOffers().ok).toBe(true); expect(store.getState().recommendation?.offerId).toBe("offer-metropulse"); expect(store.getState().history.at(-1)?.origin).toBe("agent"); });
  it("requires visible human approval, then commits exactly once", () => { const { store, service } = harness(); const preview = service.previewDataDeal({ offerId: "offer-metropulse", bidCredits: 20, durationDays: 7 }, "agent"); expect(store.getState().exchange.content.walletCredits).toBe(100); if (!preview.ok) throw new Error("preview should succeed"); const blocked = service.commitDataDeal(preview.data.token, "agent"); expect(blocked.ok ? "" : blocked.error.code).toBe("HUMAN_APPROVAL_REQUIRED"); expect(store.getState().exchange.content.walletCredits).toBe(100); expect(service.approveVisibleDeal("manual").ok).toBe(true); expect(service.commitDataDeal(preview.data.token, "agent").ok).toBe(true); expect(store.getState().exchange.content.walletCredits).toBe(78); expect(store.getState().exchange.content.access).toHaveLength(1); const replay = service.commitDataDeal(preview.data.token); expect(replay.ok ? "" : replay.error.code).toBe("PREVIEW_NOT_FOUND"); });
  it("rejects mismatched, stale, and expired tokens", () => { const mismatch = harness(); mismatch.service.previewDataDeal({ offerId: "offer-metropulse", bidCredits: 20, durationDays: 7 }); mismatch.service.approveVisibleDeal(); const mismatchResult = mismatch.service.commitDataDeal("wrong"); expect(mismatchResult.ok ? "" : mismatchResult.error.code).toBe("PREVIEW_TOKEN_MISMATCH"); const stale = harness(); stale.service.previewDataDeal({ offerId: "offer-metropulse", bidCredits: 20, durationDays: 7 }); const stalePreview = stale.store.getState().preview!; stale.store.dispatch({ type: "SET_PREVIEW", preview: { ...stalePreview, baseRevision: -1 }, entry: stale.store.getState().history.at(-1)! }); stale.service.approveVisibleDeal(); const staleResult = stale.service.commitDataDeal(stalePreview.token); expect(staleResult.ok ? "" : staleResult.error.code).toBe("PREVIEW_STALE"); const expired = harness(999_999); expired.service.previewDataDeal({ offerId: "offer-metropulse", bidCredits: 20, durationDays: 7 }); const expiredPreview = expired.store.getState().preview!; expired.store.dispatch({ type: "SET_PREVIEW", preview: { ...expiredPreview, expiresAt: 0 }, entry: expired.store.getState().history.at(-1)! }); expired.service.approveVisibleDeal(); const expiredResult = expired.service.commitDataDeal(expiredPreview.token); expect(expiredResult.ok ? "" : expiredResult.error.code).toBe("PREVIEW_EXPIRED"); });
  it("keeps manual and agent commits identical and supports undo", () => { const manual = harness(); const agent = harness(); const a = manual.service.previewDataDeal({ offerId: "offer-metropulse", bidCredits: 20, durationDays: 7 }, "manual"); const b = agent.service.previewDataDeal({ offerId: "offer-metropulse", bidCredits: 20, durationDays: 7 }, "agent"); if (!a.ok || !b.ok) throw new Error("preview should succeed"); manual.service.approveVisibleDeal(); agent.service.approveVisibleDeal(); manual.service.commitDataDeal(a.data.token, "manual"); agent.service.commitDataDeal(b.data.token, "agent"); expect(manual.store.getState().exchange).toEqual(agent.store.getState().exchange); expect(manual.service.undoLastDeal("manual").ok).toBe(true); expect(manual.store.getState().exchange.content.walletCredits).toBe(100); expect(manual.store.getState().exchange.content.access).toHaveLength(0); });
});
