import { describe, expect, it } from "vitest";
import { compareOffers, previewDeal, searchOffers } from "../domain/marketplace";
import { createSampleExchange } from "../domain/sampleExchange";

describe("marketplace engine", () => {
  it("ships a credible, stable three-offer marketplace", () => { const first = createSampleExchange(); expect(first).toEqual(createSampleExchange()); expect(first.offers).toHaveLength(3); expect(first.walletCredits).toBe(100); expect(new Set(first.offers.map((offer) => offer.id)).size).toBe(3); });
  it("searches by need and budget", () => { const found = searchOffers(createSampleExchange(), "Sydney foot traffic", 25); expect(found.map((offer) => offer.id)).toEqual(["offer-metropulse", "offer-retailflow"]); });
  it("recommends the freshest trusted offer within budget", () => { const recommendation = compareOffers(createSampleExchange()); expect(recommendation?.offerId).toBe("offer-metropulse"); expect(recommendation?.reason).toContain("40-credit budget"); });
  it("turns a low bid into an exact seller counteroffer", () => { const result = previewDeal(createSampleExchange(), { offerId: "offer-metropulse", bidCredits: 20, durationDays: 7 }, 1_000); expect(result.ok).toBe(true); if (!result.ok) return; expect(result.data.negotiation).toBe("countered"); expect(result.data.agreedCredits).toBe(22); expect(result.data.proposedContent.walletCredits).toBe(78); expect(result.data.proposedContent.access[0].sampleFields).toContain("footfall"); });
  it("rejects invalid offers, bids, and durations", () => { const content = createSampleExchange(); const missing = previewDeal(content, { offerId: "missing", bidCredits: 10, durationDays: 7 }, 1); const bid = previewDeal(content, { offerId: "offer-metropulse", bidCredits: 0, durationDays: 7 }, 1); const duration = previewDeal(content, { offerId: "offer-metropulse", bidCredits: 20, durationDays: 60 }, 1); expect(missing.ok ? "" : missing.error.code).toBe("OFFER_NOT_FOUND"); expect(bid.ok ? "" : bid.error.code).toBe("INVALID_BID"); expect(duration.ok ? "" : duration.error.code).toBe("INVALID_INPUT"); });
  it("enforces the buyer budget and prevents duplicate rentals", () => { const overBudget = createSampleExchange(); overBudget.brief.budgetCredits = 20; const budget = previewDeal(overBudget, { offerId: "offer-metropulse", bidCredits: 20, durationDays: 7 }, 1); expect(budget.ok ? "" : budget.error.code).toBe("INVALID_BID"); const unlocked = createSampleExchange(); unlocked.access.push({ offerId: "offer-metropulse", title: "MetroPulse Foot Traffic", seller: "CitySignal", paidCredits: 22, durationDays: 7, grantedAt: 1, sampleFields: [] }); const duplicate = previewDeal(unlocked, { offerId: "offer-metropulse", bidCredits: 22, durationDays: 7 }, 2); expect(duplicate.ok ? "" : duplicate.error.code).toBe("INVALID_INPUT"); });
});
